# --- Basic Site Info ---
title: "Long's Portfolio"
description: "A minimalist portfolio showcasing my projects and skills"
url: "https://iamtrusters.github.io/"   # 🔹 replace with your GitHub Pages URL
baseurl: ""   # 🔹 leave empty if hosting at root (your-username.github.io)

# --- Author Info ---
author:
  name: "Pham Long"
  email: "longkute169@gmail.com"
  github: "https://iamtrusters.github.io/"
  linkedin: "https://linkedin.com/in/phamvanlong"

# --- Theme & Build Settings ---
markdown: kramdown
theme: minima   # 🔹 Jekyll’s built-in minimalist theme
plugins:
  - jekyll-feed      # RSS feed for blog
  - jekyll-seo-tag   # Better SEO tags
  - jekyll-sitemap   # Auto-generate sitemap.xml

# --- Navigation Links (Optional) ---
nav_links:
  - name: "Home"
    url: /
  - name: "About"
    url: /about
  - name: "Projects"
    url: /projects

# --- Social Media (Optional) ---
social_links:
  github: "https://github.com/your-username"
  linkedin: "https://linkedin.com/in/your-profile"

# --- Build Exclusions ---
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
